### ISSUE TITLE
Calling unknown method: kartik\daterange\DateRangePicker::isBs4()

### ISSUE THREAD

**Issue by adilkerimov** [kartik-v/yii2-date-range#132]
The problem occurs when I use latest master.
There's no method isBs4() in your repository.

**Comment by kartik-v** [comment]
Its because you are trying to probably copy this extension (or update) manually and not updating the extension automatically via composer. Run a `composer update` to get updates to this extension with all its dependencies. You do not seem to have updated versions of dependencies - which is where you are facing this issue.
