### ISSUE TITLE
Manual typing into date_to breaks date_from value

### ISSUE THREAD

**Issue by maxgorovenko** [kartik-v/yii2-date-range#135]
## Steps to reproduce the issue
Got html page with content:
```
<?= DatePicker::widget([
	'type' => DatePicker::TYPE_RANGE,
	'name' => 'from',
	'name2' => 'to',
	'options' => ['id' => 'DateFrom'],
	'options2' => ['id' => 'DateTo'],
	'separator' => 'по',
	'value' => $from,
	'value2' => $to,
	'pluginOptions' => [
		'format' => 'dd.mm.yyyy',
		'autoclose' => true,
		'todayHighlight' => true,
		'language' => 'ru'
	]
]); ?>
```

It draws two fields DateFrom and DateTo, everything goes well untill I writing dates manualy via keyboard.

I got '01.01.2019' at DateFrom field and I want to write 31.01.2019 into DateTo field. I typing '31.01.' - DateFrom still ok. When I add '2' (to write 2019) to field DateTo, it becomes '31.01.2' and in this moment field DateFrom changes its value to '31.01.2'.

Recorded the video
![Alt text](https://api.monosnap.com/rpc/file/download?id=sxGiXsNkH3JuVZ7bALPZmPss75Kp5T)

## Expected behavior and actual behavior
I don't want the widget change field value while I'm typing to another field. But It does.

When I'm typing value '31.01.2019' to DateTo field, the value of DateFrom field was changed from '01.01.2019' to '31.01.2'. I don't need this.

May be there is any option, but I've tried everything and it did not help me.
## Environment
Yii2, php7.0

#### Browsers
Google Chrome

#### Operating System
Mac OS X

**Comment by kartik-v** [comment]
This issue is not related to this extension or widget. You are talking about [kartik-v/yii2-widget-datepicker extension](https://github.com/kartik-v/yii2-widget-datepicker) and this [demo in the docs deals with your use case](http://demos.krajee.com/widget-details/datepicker#markup-range).

The behavior is provided by the third party plugin `bootstrap-datepicker`. You can cross check that in the demo above it works fine and if there is an issue with your specific date format it needs to be reported with the plugin author
