### ISSUE TITLE
Clicking "today" the first time on an empty field doesn't fill it

### ISSUE THREAD

**Issue by germansokolov13** [kartik-v/yii2-date-range#33]
http://demos.krajee.com/date-range
The trouble is visible on your example. There is an empty daterange field configured with dropdown format. If you click it and choose "Today" nothing happens. You need to choose something else first to choose "today" or have not empty but rather today as a default value.

It seems the problem exists because the plugin does not support emptiness though your widget still tries to support it. I think internally the plugin is already at "Today" and that's why you can't make it "Today" again. Not supporting emptiness is sad because that way you can't use the widget for filtering the grid.

**Comment by kartik-v** [comment]
You may need to report this as an enhancement request on the plugin author's project page.

This is only for cases where you set the presets as mentioned in the widget usage example.
Unfortunately the preset highlighted by default for an empty value is not something we can control via this widget. Its inbuilt within the plugin and the plugin defaults an empty value to the **today** selection by default.

Workaround currently if the plugin is not enhanced:
a) have some other value set to default instead of null so that today is not selected by default
b) if you do not want above .. and need to select today then user has to currently select some other preset and then click today.
