### ISSUE TITLE
Bug on kartik\yii2-grid with PJAX

### ISSUE THREAD

**Issue by markmarco16** [kartik-v/yii2-date-range#72]
Hello,

I trie used this daterange on filter with ModelSearch,  but when i set PJAX true and clicking on the date field does not open the menu.

How to reproduce:

```
use kartik\grid\GridView;
use kartik\daterange\DateRangePicker;

...

                         [
                            'label' => Yii::t('app', "Confirmation Date"),
                            'attribute' => 'confirmation_date',
                            'value' => 'confirmation_date',
                            'format' => 'date',
                            'filter' => DateRangePicker::widget([
                                'model' => $searchModel,
                                'language' => 'es',
                                'attribute' => 'confirmation_date',
                                'convertFormat' => true,
                                'presetDropdown' => true,
                                'pluginOptions' => [
                                    'locale' => [
                                        'format' => 'Y-m-d',
                                    ],
                                ],
                            ]),
                        ],

...

'pjax'=>true,

```

Version

 kartik-v/yii2-date-range (dev-master 70febdb)
    Checking out 70febdb463b86d08287ee4df60991a524720654f

**Comment by kartik-v** [comment]
Will not work the way you have... it should work with one of the following

1. either you use the built in kartik GridView constant `GridView::FILTER_DATE_RANGE` to set your filter

OR

2. if you are manually rendering the widget like above ... you need to manually handle your widget initialization. Since you are using a krajee widget it is simple... by setting the widget config `pjaxContainerId` to be the same as your gridview's pjax container settings. If you do not want to go through these all .. try option 1 before.
