### ISSUE TITLE
Update moment library to latest release

### ISSUE THREAD

**Issue by thiagotalma** [kartik-v/yii2-date-range#91]
It's time to update?

**Comment by samuelroxo** [comment]
I think so.

**Comment by kartik-v** [comment]
Resolved via v1.6.8 update (still in dev-master) --- here 90450cd.

**Comment by thiagotalma** [comment]
@kartik-v, why do not you include the momentjs as a dependency instead of adding the files in the project?

**Comment by kartik-v** [comment]
Various reasons - because of specific customizations done to the widget... I have seen this break with other plugins with newer versions of them and hence some level of testing is needed before updating. Secondly, dependency tracking anyway needs to be done in that case to use specific versions. 

Thirdly because of the way currently yii2-krajee-base uses AssetBundles... it needs the minified assets (CSS and JS) to be available in the repo in the same folder as the JS and CSS... lastly some of these repos have a lot of unwanted files which also need to be specifically excluded.
